# LOOPS PROGRAMS 

# PALINDROME OR NOT
it reverse calculate the value can be same that is called palindrome.
eg: 434=434,
    Amma=Amma

In [1]:
#To find the given number is palindrome or not:

n=int(input("enter the value n="))
x=n
s=0
while(n>0):
    r=n%10
    s=s*10+r
    n=n//10
    print(s)
if(s==x):
    print("it is a palindrome")
else:
    print("it is not a palindrome")

enter the value n=121
1
12
121
it is a palindrome


In [2]:
#To find the given number from 1 to 50 print palindrome or not:

for i in range(1,51):
    x=i
    s=0
    while(x>0):
        r=x%10
        s=s*10+r
        x=x//10
    if(s==i):
        print(i,end=' ')

1 2 3 4 5 6 7 8 9 11 22 33 44 

# AMSTRONG OR NOT

   EXAMPLE:153=1^3+5^3+3^3=1+125+27=153 IT IS AMSTRONG NUMBER,
           124=1^3+2^3+4^3=1+8+64=73    IT IS NOT A AMSTRONG NUMBER.

In [3]:
# write a program find the given number is armstrong or not:

n=int(input("enter the value n="))
x=n
s=0
while(n>0):
    r=n%10
    s=s+r**3
    n=n//10
    print(s)
if(s==x):
    print("it is a amstrong")
else:
    print("it is not a amstrong")

enter the value n=153
27
152
153
it is a amstrong


In [4]:
# write a program find the given numbers from 1 to 1000 which is amstrong or not:

for i in range(1,1001):
    x=i
    s=0
    while(x>0):
        r=x%10
        s=s+r**3
        x=x//10
    if(s==i):
        print(i)

1
153
370
371
407


# ADD N NUMBERS

EXAMPLE:1+2+3+4+5=15

In [5]:
# Find the n number add them from 1 to n:

n=int(input("enter the value n="))
s=0
for i in range(1,n+1):
    s=s+i
    print(s,end=' ')

enter the value n=5
1 3 6 10 15 

In [6]:
n=5
i=1
s=0
while(n>=i):   # or (i<=n)
    s=s+i
    i=i+1
    print(s)

1
3
6
10
15


# FACTORIAL

EXAMPLE: 5FACTORIAL=5 INTO 4 INTO 3 INTO 2 INTO 1=120

In [7]:
# factorial 

n=int(input("enter the value n="))
i=1
f=1
while(i<=n):  # or (n>=i)
    f=f*i
    i=i+1
    print(f)

enter the value n=5
1
2
6
24
120


In [8]:
n=int(input("enter the value n="))
f=1
for i in range(1,n+1):
    f=f*i
    print(f)

enter the value n=5
1
2
6
24
120


In [9]:
n=int(input("enter the value n="))
f=1
for i in range(n,0,-1):
    f=f*i
print(f)

enter the value n=5
120


In [10]:
# 5 to 1 factorial:

f=1
i=5
while(i>=1):
    f=f*i
    i=i-1
    print(f)

5
20
60
120
120


# STRONG NUMBER

EXAMPLE==145-FACTORIAL=1 FACTORIAL+4 FACTORIAL+5 FACTORIAL=1+24+120=145 THEN IT IS A STRONG NUMBER._____________________________
153=1+120+6=127 IT IS NOT A STRONG NUMBER.

In [11]:
# Given number is  strong number or not:

n=int(input("enter the value n="))
x=n
s=0
while(n>0):
    r=n%10
    f=1
    for i in range(1,r+1):
        f=f*i
    s=s+f
    n=n//10
    print(s)
if(s==x):
    print("it is a strong number")
else:
    print("it is not a strong number")

enter the value n=145
120
144
145
it is a strong number


In [12]:
# print from 1 to 1000 strong number:

for i in range(1,1001):
    n=i
    s=0
    while(n>0):
        r=n%10
        f=1
        for j in range(1,r+1):
            f=f*j
        s=s+f
        n=n//10
    if(s==i):
        print(i)

1
2
145


# ADAM NUMBER OR NOT 

A Number is said to be an adam number if the reverse of square of the number is equal to the square of the reverse of the number.______EXAMPLE:13=13 INTO 13=169___31=31 INTO 31=961 ANY ONE REVERSE THE NUMBER. #THEN SAME NUMBER IS CALLED ADAM NUMBER.

In [13]:
# Given number is adam or not:

n=int(input("enter the value n="))
x=n**2
s=0
while(n>0):
    r=n%10
    s=s*10+r
    n=n//10
y=s**2
s1=0
while(x>0):
    r=x%10
    s1=s1*10+r
    x=x//10
if(s1==y):
    print("it is a adam number")
else:
    print("it is not a adam number")

enter the value n=12
it is a adam number


In [14]:
#print Adam number from 1 to 1000:

for i in range(1,1001):
    n=i
    s=0
    x=n**2
    while(n>0):
        r=n%10
        s=s*10+r
        n=n//10
    y=s**2
    s1=0
    while(x>0):
        r=x%10
        s1=s1*10+r
        x=x//10
    if(s1==y):
        print(i,end=' ')

1 2 3 10 11 12 13 20 21 22 30 31 100 101 102 103 110 111 112 113 120 121 122 130 200 201 202 210 211 212 220 221 300 301 310 311 1000 

# SHERLOCK NUMBER OR NOT

N=145=1+4+5=10._____Then 10 is divided by 2 remainder is zero sherlock number.___remainder is not zero not sherlock number.?

In [15]:
# Sherlock or not given nuumber 

n=int(input("enter the value n="))
s=0
while(n>0):
    r=n%10
    s=s+r
    n=n//10
    print(s)
if(s%2==0):
    print("sherlock number")
else:
    print("not sherlock number")

enter the value n=145
5
9
10
sherlock number


In [16]:
# print sherlock number from 1 to 1000:

for i in range(1,1001):
    n=i
    s=0
    while(n>0):
        r=n%10
        s=s+r
        n=n//10
    if(s%2==0):
        print(i,end=' ')

2 4 6 8 11 13 15 17 19 20 22 24 26 28 31 33 35 37 39 40 42 44 46 48 51 53 55 57 59 60 62 64 66 68 71 73 75 77 79 80 82 84 86 88 91 93 95 97 99 101 103 105 107 109 110 112 114 116 118 121 123 125 127 129 130 132 134 136 138 141 143 145 147 149 150 152 154 156 158 161 163 165 167 169 170 172 174 176 178 181 183 185 187 189 190 192 194 196 198 200 202 204 206 208 211 213 215 217 219 220 222 224 226 228 231 233 235 237 239 240 242 244 246 248 251 253 255 257 259 260 262 264 266 268 271 273 275 277 279 280 282 284 286 288 291 293 295 297 299 301 303 305 307 309 310 312 314 316 318 321 323 325 327 329 330 332 334 336 338 341 343 345 347 349 350 352 354 356 358 361 363 365 367 369 370 372 374 376 378 381 383 385 387 389 390 392 394 396 398 400 402 404 406 408 411 413 415 417 419 420 422 424 426 428 431 433 435 437 439 440 442 444 446 448 451 453 455 457 459 460 462 464 466 468 471 473 475 477 479 480 482 484 486 488 491 493 495 497 499 501 503 505 507 509 510 512 514 516 518 521 523 525 527 5

# FIBONACCI SERIES

EXAMPLE:0+1+1+2+3+5+8+13+21+34+55+89__________a=0 b=1 a+b=c next b=a c=b a+b=c.......

In [17]:
# Display fibonacci series:

n=int(input("enter the value n="))
a=0
b=1
for i in range(1,n+1):
    c=a+b
    print(c)
    a=b
    b=c

enter the value n=10
1
2
3
5
8
13
21
34
55
89


# PRIME NUMBER OR COMPOSIT NUMBER

Which are exactly divisible by one and itself. EXAMPLE:1 INTO 2=2 AND 2 INTO 1=2,3 INTO 1=3 AND 1 INTO 3=3 PRIME NUMBER,____________________
1 INTO 10=10 AND 2 INTO 5=10 AND 5 INTO 2=10 AND 10 INTO 1=10 COMPOSIT NUMBER.

In [18]:
# Find the prime or composit number:

n=int(input("enter the value n="))
c=0
for i in range(1,n+1):
    if(n%i==0):
        c=c+1
if(c==2):
    print("prime number")
else:
    print("composit number")

enter the value n=5
prime number


In [19]:
# print from 1 to 1000 prime numbers:

for i in range(1,1001):
    n=i
    c=0
    for j in range(1,n+1):
        if(n%j==0):
            c=c+1
    if(c==2):
        print("no of prime number is:",i)

no of prime number is: 2
no of prime number is: 3
no of prime number is: 5
no of prime number is: 7
no of prime number is: 11
no of prime number is: 13
no of prime number is: 17
no of prime number is: 19
no of prime number is: 23
no of prime number is: 29
no of prime number is: 31
no of prime number is: 37
no of prime number is: 41
no of prime number is: 43
no of prime number is: 47
no of prime number is: 53
no of prime number is: 59
no of prime number is: 61
no of prime number is: 67
no of prime number is: 71
no of prime number is: 73
no of prime number is: 79
no of prime number is: 83
no of prime number is: 89
no of prime number is: 97
no of prime number is: 101
no of prime number is: 103
no of prime number is: 107
no of prime number is: 109
no of prime number is: 113
no of prime number is: 127
no of prime number is: 131
no of prime number is: 137
no of prime number is: 139
no of prime number is: 149
no of prime number is: 151
no of prime number is: 157
no of prime number is: 163
no 

# PERFECT NUMBNER OR NOT 

EXAMPLE:N=6__1 INTO 6 =6,2 INTO 6 =6,3 INTO 2=6___1+2+3=6 THIS IS PERFECT NUMBER.___________________
N=8___1 INTO 8=8,2 INTO 4=8,4 INTO 2=8___1+2+4=7 THIS IS NOT PERFECT NUMBER.

In [20]:
# write a program to find the given number is perfect number or not:

n=int(input("enter the value n="))
c=0
for i in range(1,n):
    if(n%i==0):
        c=c+i
if(c==n):
    print("perfect number")
else:
    print("not perfect number")

enter the value n=6
perfect number


In [21]:
# print perfect number from 1 to 1000:

for i in range(1,1001):
    n=i
    c=0
    for j in range(1,n):
        if(n%j==0):
            c=c+j
    if(c==n):
        print(i,end=' ')

6 28 496 